### PR TITLE
camelCase -> snake_case

### LINKED ISSUE #151: camelCase -> snake_case
To be more pythonic, the library should move from camelCase  to snake_case. This is likely a holdover from the original library that was written in Java.

### PR DESCRIPTION
**Pull request by barrust**
resolves #151

### CODE REVIEW

**Review by lababidi — CHANGES_REQUESTED** [review]
Can you alias the snake case name to a camel case name to prevent breaking?

**Comment by lababidi** [comment]
100% agreed. You can put the deprecated decorator

**Comment by barrust** [comment]
Added a `deprecated` decorator and a `fail_after` decorator to have tests fail if they are not removed prior to a specific version. I set that to be 3.1.14 but that can be changed easily enough. 

What I did find is that a lot of the parser code is not directly tested. I put stub tests in for them but wanted that to be tracked.

**Review by lababidi — APPROVED** [review]
fantastic!

**Comment by barrust** [comment]
Thanks! I built the two decorators in another project and it was fairly straight forward to make them work here!

**Pull request merged**
