### PR TITLE
Armenian Language for cleared_text

### PR DESCRIPTION
**Pull request by akatcha**
Hello, this was something I tried to put together this weekend with Armenian News Analysis.  
Issue: [https://github.com/goose3/goose3/issues/38](https://github.com/goose3/goose3/issues/38)

Though the test I wrote passes, there is one thing that is causing this to not fully work as intended...
```
Python 3.4.3 (default, Nov 28 2017, 16:41:13)                                     
[GCC 4.8.4] on linux                                                              
Type "help", "copyright", "credits" or "license" for more information.            
>>> from goose3 import Goose                                                      
>>> from goose3.text import StopWordsArmenian                                     
>>> url='http://www.panarmenian.net/arm/news/250968/'                             
>>> g = Goose({'stopwords_class':StopWordsArmenian})                              
>>> article = g.extract(url=url)                                                  
>>> article.cleaned_text                                                          
''                                                                                
>>> print(article.cleaned_text)         
```

The code above is the same as my test case.  My test case passes but I am unsure why this is failing.  Let me know if you are also running into this issue

I pulled the stopwords from here: https://github.com/Kronuz/Xapiand/blob/master/stopwords/hy.txt

### CODE REVIEW

**Comment by Andrew-Katcha** [comment]
Todo: Once this is working as intended, I will update the documentation for `Goose in Armenian` :)

**Comment by barrust** [comment]
This looks great! So a few comments: 
1) After looking more at the code for the different languages, it seems that we could (I think) get away without having to use the stop-word class that is Armenian specific. I think we could accomplish the same using: 
``` python
with Goose3({'target_language': 'hy'}) as g:
    article = g.extract(url=url)
    print(article.title)
```
Another reason this could be worthwhile is that if the meta-language is set on the page it should automatically try to use the correct language. 
2) As for why it isn't working in your terminal, I believe that is because your terminal is auto printing to a different encoding. Not positive but it might be something to think about.

**Comment by Andrew-Katcha** [comment]
Good feedback!

So I ran this in ubuntu linux 16.04 and got this output.  Not sure why this happening.  I ran the Korean version and it worked, but for Armenian I got this:
```
>>> url='http://www.panarmenian.net/arm/news/250968/'
>>> g = Goose({'target_language': 'hy'})
>>> article = g.extract(url=url)
>>> print(article.title)
ÕÕ¸ÖÕ±Õ¡Õ£Õ¥Õ¿. Ô±Õ¤ÖÕ¢Õ¥Õ»Õ¡Õ¶Õ¡Õ¯Õ¡Õ¶ Ö Õ©Õ¸ÖÖÖ
                                                       Õ¡Õ¯Õ¡Õ¶ Õ°Õ¡Ö
                                                                     Õ¥ÖÕ¡ÕµÕ«Õ¶ Õ­Õ´Õ¢Õ¥ÖÕ¶ Õ¡Õ¯Õ¿Õ«Õ¾Õ¡ÖÕ¥Õ¬ Õ¥Õ¶
```
Before I continue working on this, I wanted to figure out why this is happening.

**Comment by barrust** [comment]
Yeah, I am getting the same on linux here. I will wait on this until you are more comfortable!

**Comment by barrust** [comment]
@akatcha is this something you would still like to pursue in merging into Goose3?

**Comment by barrust** [comment]
closing due to no updates; please re-open this PR if this is still of interest.

**Pull request closed without merging**
