### PR TITLE
publishdate extractor

### PR DESCRIPTION
**Pull request by timoilya**
* add one publish date tag
* fix extraction publish date
* extracting authors via KNOWN_AUTHOR_PATTERNS

### CODE REVIEW

**Comment by timoilya** [comment]
added extracting authors via KNOWN_AUTHOR_PATTERNS to this pull request

**Comment by timoilya** [comment]
@barrust please update version in pypi

**Comment by barrust** [comment]
@timoilya done

**Comment by timoilya** [comment]
> @timoilya done

thanks!

**Pull request merged**
