### PR TITLE
Basic logging, typing and deprecate python3.5 and 3.6

### PR DESCRIPTION
**Pull request by Jonakemon**
I've done a few to-do's spread here and there throughout the project. Biggest change - code wise - is refactoring the meta_lang and publish_date_to_utc logic to separate methods.

### CODE REVIEW

**Review by lababidi — APPROVED** [review]
Really nice work. Thank you for the contribution!

**Comment by Jonakemon** [comment]
@lababidi I've changed the meta_lang and publish_date_to_utc refactor a tiny bit so that the tests would pass. Could you re-check it again? That should also trigger the tests to work.

**Comment by lababidi** [comment]
Only recommendation is to switch from logger.debug to logger.error or warning. 

Looks great!

**Comment by Jonakemon** [comment]
Done! Thanks!

**Review by lababidi — APPROVED** [review]

**Pull request merged**
