### PR TITLE
add test for #116 and resolve a deprication warning for dateutil.parser

### PR DESCRIPTION
**Pull request by barrust**
@Pradhvan

### CODE REVIEW

**Comment by Pradhvan** [comment]
@barrust looks like the work is almost done. Is there anything you want me to update in the PR ?

**Comment by barrust** [comment]
Nope! This should be everything; wanted to let you see how tests can be implemented. If you see any other issues, please let the group know!

**Comment by Pradhvan** [comment]
@barrust thanks. Any idea when would the next release be ?

**Comment by barrust** [comment]
@Pradhvan it will probably be in the next day or so. I have another PR I want to get in for a new feature to close another issue and once that is in, I will likely push out a new version.

**Comment by Pradhvan** [comment]
Great 👍🏾 looking forward to it. 😄

**Pull request merged**
