### PR TITLE
Update score of all parents

### PR DESCRIPTION
**Pull request by skruse**
Update all parents (instead of only parent and parentparent) to not miss deeply nested content.

### CODE REVIEW

**Comment by dlrobertson** [comment]
Seems to extract the wrong text from http://newyork.cbslocal.com/2012/06/08/bc-morning-show-american-hero-kelly-malloy

**Comment by skruse** [comment]
If one changes the parameters to `upscore*(1.5/(depth+0.5)` it passes all tests (at least locally for me, sorry that I did not check this before).  Will try again tomorrow.

**Comment by dlrobertson** [comment]
No problem! Thanks for working on this.

**Comment by skruse** [comment]
I decreased the propagated score, so that all previous tests pass, and added a test for the page that failed for me.

**Comment by dlrobertson** [comment]
@barrust LGTM. You have any thoughts?

**Comment by barrust** [comment]
This looks good to me!

**Pull request merged**
